### ISSUE TITLE
8 Story Points - 1.1 Categorize products 

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#16]
As a seller, I want to put my product in a certain category so that I can appeal to more buyers #1 
## Note
categories and products are a one to many relationship, a category consists of many products, but pertinently **Each product has one and only one category**

## Done Criteria
Put a product into a category so that buyers who search that category see my product
## Tasks
- [x] #81
- [ ] #82
- [x] add a dropdown menu that allows sellers to select which category they wish to post their listing in
- [x] add tests to JUnit

**Comment by jlindsey001** [comment]
Done Criteria
Sellers on the website can effectively associate their product or service with a category.
